export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const GET_USER_COMPLAINTS = 'GET_USER_COMPLAINTS';
export const GET_USER_COMPLAINTS_SUCCESS = 'GET_USER_COMPLAINTS_SUCCESS';
export const GET_USER_COMPLAINTS_FAILURE = 'GET_USER_COMPLAINTS_FAILURE';
export const UPDATE_COMPLAINT_STATUS = 'UPDATE_COMPLAINT_STATUS'; // for admin
export const UPDATE_COMPLAINT_STATUS_SUCCESS = 'UPDATE_COMPLAINT_STATUS_SUCCESS'; 
export const UPDATE_COMPLAINT_STATUS_FAILURE = 'UPDATE_COMPLAINT_STATUS_FAILURE';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';
export const GET_ALL_COMPLAINTS = 'GET_ALL_COMPLAINTS';

